import {readFile,writeFile,mkdir} from 'node:fs/promises';
const read=file=>readFile(new URL(file,import.meta.url),'utf8');
const strip=source=>source.replace(/^import .* from ['"].*['"];?\s*$/gm,'').replace(/^export /gm,'');
const kernel=strip(await read('src/kernel.js'));
const worker=kernel+'\n'+strip(await read('src/worker.js'));
const documentModel=strip(await read('src/document.js'));
const renderer=strip(await read('src/renderer.js'));
const app=strip(await read('src/app.js')).replace("new URL('./worker.js', import.meta.url)",'AXIOM_WORKER_URL');
const script=`const AXIOM_WORKER_URL=URL.createObjectURL(new Blob([${JSON.stringify(worker)}],{type:'text/javascript'}));\n${kernel}\n${documentModel}\n${renderer}\n${app}`;
const styles=await read('src/styles.css');
const shell=await read('src/shell.html');
const html=shell.replace('<!-- AXIOM_STYLES -->',()=>`<style id="axiom-style">${styles}</style>`).replace('<!-- AXIOM_SCRIPT -->',()=>`<script type="module">\n${script.replace(/<\/script/gi,'<\\/script')}\n</script>`);
await writeFile(new URL('index.html',import.meta.url),html);
await mkdir(new URL('dist/',import.meta.url),{recursive:true});
await writeFile(new URL('dist/index.html',import.meta.url),html);
console.log(`Built standalone index.html (${(Buffer.byteLength(html)/1024).toFixed(1)} KiB). No runtime dependencies.`);
