import test from 'node:test';
import assert from 'node:assert/strict';
import { DocumentStore,validateDocument,beamExample,numericalExample,blankExample,createRegion } from '../src/document.js';
import {WorksheetKernel} from '../src/kernel.js';
for(const [name,f]of[['beam',beamExample],['numerical sandbox',numericalExample],['blank',blankExample]])test(name+' calculates without errors',()=>{const d=validateDocument(f()),r=new WorksheetKernel().calculate(d);assert.equal(r.errors,0,JSON.stringify(r.results));});
test('transactions undo and redo',()=>{const s=new DocumentStore(blankExample()),old=s.document.name;s.transaction('Rename',d=>d.name='Test');assert.equal(s.document.name,'Test');s.undo();assert.equal(s.document.name,old);s.redo();assert.equal(s.document.name,'Test');});
test('transaction failure rolls back',()=>{const s=new DocumentStore(blankExample());assert.throws(()=>s.transaction('Broken',d=>{d.name='Changed';throw Error('no');}));assert.equal(s.document.name,'Untitled worksheet');});
test('coalesced transaction',()=>{const s=new DocumentStore(blankExample());s.begin();s.document.name='a';s.begin();s.document.name='ab';s.commit('Typing');assert.equal(s.undoStack.length,1);s.undo();assert.equal(s.document.name,'Untitled worksheet');});
test('undo creates redo branch',()=>{const s=new DocumentStore(blankExample());s.transaction('a',d=>d.name='a');s.undo();s.transaction('b',d=>d.name='b');assert.equal(s.redoStack.length,0);});
test('invalid document rejected',()=>assert.throws(()=>validateDocument({version:12}),/not a supported/));
test('duplicates rejected',()=>{const d=blankExample();d.regions.push({...d.regions[0]});assert.throws(()=>validateDocument(d),/Duplicate/);});
test('foreign images rejected',()=>{const d=blankExample();d.regions.push(createRegion('image',{data:'https://example.org/x.png'}));assert.throws(()=>validateDocument(d),/embedded/);});
test('SVG images rejected',()=>{const d=blankExample();d.regions.push(createRegion('image',{data:'data:image/svg+xml;base64,PHN2Zz4='}));assert.throws(()=>validateDocument(d),/embedded/);});
test('geometry clamped',()=>{const d=blankExample();d.regions[0].x=-999;d.regions[0].w=10000;d.regions[0].page=1000;const r=validateDocument(d).regions[0];assert.equal(r.x,20);assert.equal(r.w,860);assert.equal(r.page,99);});
